### ISSUE TITLE
Exported default class declaration not supported

### ISSUE THREAD

**Issue by jfparadis** [Agoric/make-importer#12]
From Test 262 
https://github.com/tc39/test262/blob/master/test/language/module-code/eval-export-dflt-cls-anon.js

```js
/*---
description: >
    Default "anonymous" class declaration is correctly initialized upon
    evaluation
esid: sec-moduleevaluation
info: |
    [...]
    16. Let result be the result of evaluating module.[[ECMAScriptCode]].
    [...]
    15.2.3.11 Runtime Semantics: Evaluation
    ExportDeclaration : export default ClassDeclaration
    [...]
    3. Let className be the sole element of BoundNames of ClassDeclaration.
    4. If className is "*default*", then
       a. Let hasNameProperty be ? HasOwnProperty(value, "name").
       b. If hasNameProperty is false, perform SetFunctionName(value,
          "default").
       c. Let env be the running execution context's LexicalEnvironment.
       d. Perform ? InitializeBoundName("*default*", value, env).
    5. Return NormalCompletion(empty).
flags: [module]
---*/

export default class { valueOf() { return 45; } }
import C from './eval-export-dflt-cls-anon.js';

assert.sameValue(new C().valueOf(), 45, 'binding initialized');
assert.sameValue(C.name, 'default', 'correct name is assigned');
```

This is a different issue than https://github.com/Agoric/transform-module/issues/3 and since it occurs inside Babel, not the `transform-module` code.

**Steps to reproduce**

In `make-importer`, replace `moddir/index.js` with:
```js
export default class { valueOf() { return 45; } }
```
Then execute:
```sh
$ node -r esm test/test-moddir.js 
TAP version 13
# import moddir
(node:24654) ExperimentalWarning: The fs.promises API is experimental
not ok 1 unexpected exception
  ---
    operator: notEqual
    expected: |-
      [TypeError: Property arguments[0] of CallExpression expected node to be of a type ["Expression","SpreadElement","JSXNamespacedName","ArgumentPlaceholder"] but instead got "ClassDeclaration"]
    actual: |-
      [TypeError: Property arguments[0] of CallExpression expected node to be of a type ["Expression","SpreadElement","JSXNamespacedName","ArgumentPlaceholder"] but instead got "ClassDeclaration"]
    at: Test._1cc‍.r.test (~/projects/make-importer/test/test-moddir.js:59:7)
    stack: |-
      TypeError: Property arguments[0] of CallExpression expected node to be of a type ["Expression","SpreadElement","JSXNamespacedName","ArgumentPlaceholder"] but instead got "ClassDeclaration"
          at validate (~/projects/make-importer/node_modules/@babel/types/lib/definitions/utils.js:131:13)
          at validator (~/projects/make-importer/node_modules/@babel/types/lib/definitions/utils.js:100:7)
          at Object.validate (~/projects/make-importer/node_modules/@babel/types/lib/definitions/utils.js:201:7)
          at validateField (~/projects/make-importer/node_modules/@babel/types/lib/validators/validate.js:22:9)
          at validate (~/projects/make-importer/node_modules/@babel/types/lib/validators/validate.js:16:3)
          at builder (~/projects/make-importer/node_modules/@babel/types/lib/builders/builder.js:46:27)
          at Object.CallExpression (~/projects/make-importer/node_modules/@babel/types/lib/builders/generated/index.js:273:31)
          at PluginPass.ExportDefaultDeclaration (~/projects/make-importer/node_modules/@agoric/transform-module/dist/transform-module.cjs.js:276:30)
          at newFn (~/projects/make-importer/node_modules/@babel/traverse/lib/visitors.js:193:21)
          at NodePath._call (~/projects/make-importer/node_modules/@babel/traverse/lib/path/context.js:53:20)
  ...

1..1
# tests 1
# pass  0
# fail  1
```

Expected result: code should not throw in Babel

**Comment by jfparadis** [comment]
Thanks @michaelfig, tests are much better. Here are more cases:

**Steps to reproduce**
In `make-importer`, replace `moddir/index.js` with:
```js
export default (class { valueOf() { return 45; } });
import C from './index.js';

if (C.name !== 'default') {
  throw new TypeError('correct name is not assigned');
}
```
Then execute:
```sh
$ node -r esm test/test-moddir.js 
```
Actual result: [TypeError: correct name is not assigned]
Expected result: same as node's native import:
```sh
$ node -r esm test/moddir/index.js
// no error
```

**Comment by jfparadis** [comment]
*Steps to reproduce 2**
In `make-importer`, replace `moddir/index.js` with:
```js
export default (function() { return 99; });
import f from './index.js';

if (f.name !== 'default') {
  throw new TypeError('correct name is not assigned');
}
```
Then execute:
```sh
$ node -r esm test/test-moddir.js 
```
Actual result: [TypeError: correct name is not assigned]
Expected result: same as node's native import:
```sh
$ node -r esm test/moddir/index.js
// no error
```

**Comment by jfparadis** [comment]
**Steps to reproduce 3**
In `make-importer`, replace `moddir/index.js` with:
```js
export default (function* () { return 24601; });
import g from './index.js';

if (g.name !== 'default') {
  throw new TypeError('correct name is not assigned');
}
```
Then execute:
```sh
$ node -r esm test/test-moddir.js 
```
Actual result: [TypeError: correct name is not assigned]
Expected result: same as node's native import:
```sh
$ node -r esm test/moddir/index.js
// no error
```
